### ISSUE TITLE
yarn build leads to Failed to compile

### ISSUE THREAD

**Issue by ww8912188** [harshzalavadiya/react-multi-select-component#150]
After I have this package, I got:
```
➜  frontend git:(feature/project-report) ✗ yarn build
yarn run v1.22.4
$ GENERATE_SOURCEMAP=false react-scripts build
Creating an optimized production build...
Failed to compile.

Failed to minify the bundle. Error: static/js/main.24b8b55e.js from UglifyJs
Unexpected token: name (e) [static/js/main.24b8b55e.js:84829,4]
    at /Users/user/gitlab/frontend/node_modules/react-scripts/scripts/build.js:128:23
    at /Users/user/gitlab/frontend/node_modules/webpack/lib/Compiler.js:269:13
    at Compiler.emitRecords (/Users/user/gitlab/frontend/node_modules/webpack/lib/Compiler.js:375:38)
    at /Users/user/gitlab/frontend/node_modules/webpack/lib/Compiler.js:262:10
    at /Users/user/gitlab/frontend/node_modules/webpack/lib/Compiler.js:368:12
    at next (/Users/user/gitlab/frontend/node_modules/tapable/lib/Tapable.js:218:11)
    at Compiler.<anonymous> (/Users/user/gitlab/frontend/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at next (/Users/user/gitlab/frontend/node_modules/tapable/lib/Tapable.js:220:14)
    at /Users/user/gitlab/frontend/node_modules/sw-precache-webpack-plugin/lib/index.js:98:18
Read more here: http://bit.ly/2tRViJ9

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Delete this package, it works smoothly. Can someone shining some light on this issue?

**Comment by harshzalavadiya** [comment]
@ww8912188,

This shouldn't happen can you provide minimal sample?, is it CRA, Nextjs repository

**Comment by harshzalavadiya** [comment]
Looking at the error logs says that you might be passing some unnecessary prop
- this component does not accept prop "name" if added removing might solve this
- but it looks like tapable module is causing this error and this component is not dependent upon it

**Comment by ww8912188** [comment]
We could not privide the source code. Sorry about that, anyway.
